# This is a starting workflow for building with GitHub Actions
name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # Set up the build environment
      - run: npm ci --prefix "./complete-application/"

      # Build
      - name: Copy our kickstart file over so it gets picked up
        run: mkdir faDockerComposeFilePath/ && cp -r kickstart faDockerComposeFilePath/
      - name: Start FusionAuth
        uses: fusionauth/fusionauth-github-action@0.0.4
        with:
          FUSIONAUTH_VERSION: 1.48.3
      - name: List directory
        run: ls -l faDockerComposeFilePath/kickstart
      - name: Install npm dependencies
        run: |
          npm install
          npx playwright install-deps
          npx playwright install
        working-directory: ./complete-application
      - name: Start app
        run: npm run dev & # & in background
        working-directory: ./complete-application

      - name: Run Playwright tests
        run: npx playwright test --project=chromium
        working-directory: ./complete-application
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-screenshot
          path: complete-application/screenshot.png
          retention-days: 2
      # Done!
